# All values in no of frames
BACKGROUND_COLOR: #ABABAB
FRAME_RATE: 60
FIX_CROSS_TIME: 48 
NO_BLOCKS: 4
NO_TRAINING_TRIALS: 4
FIX_CROSS_COLOR: black
FIX_CROSS_SIZE: 0.1
STIM_LETTERS: ["<<<<<", ">>>>>", "<<><<", ">><>>"]
STIM_SIZE: 0.1
STIM_COLOR: black
STIM_TIME: 60
INTERSTIM_TIME: 60
REACTION_TIME: 60
REACTION_KEYS: [lshift, rshift]
LEFT_CONG_PROPORTION: 1
RIGHT_CONG_PROPORTION: 1
RIGHT_INCONG_PROPORTION: 1
LEFT_INCONG_PROPORTION: 1

